# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx webpack -p

      - name: WordPress Plugin Deploy
        if: startsWith(github.ref, 'refs/tags/')
        uses: 10up/action-wordpress-plugin-deploy@1.4.1
        env:
          SLUG: acf-commonmark
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          
      - name: Release
        run: |
          rm -fr .github node_modules .travis.yml .editorconfig .gitignore .prettierrc.js deploy.sh deploy-github.sh tests codeception.dist.yml
          zip -r acf-commonmark.zip . -x *.git*

      - uses: actions/upload-artifact@master
        with:
          name: acf-commonmark.zip
          path: acf-commonmark.zip
